name: test
on: [push]

env:
  DENO_VERSION: v1.x

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: denoland/setup-deno@v1
  #       with:
  #         deno-version: ${{ env.DENO_VERSION }}
  #     - run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-java@v2
      #   with:
      #     distribution: 'adopt'
      #     java-version: '16'
      # - run: java -version
      # - uses: DeLaGuardo/setup-clojure@master
      #   with:
      #     tools-deps: latest
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - run: make test
